### ISSUE TITLE
Doesn't work in Emacs 25?

### ISSUE THREAD

**Issue by WorldsEndless** [tam17aki/ace-isearch#19] opened 2015-11-26 16:39 UTC
Running a newly-built copy of emacs 25:

GNU Emacs 25.1.50.1 (x86_64-suse-linux-gnu, X toolkit, Xaw3d scroll bars) of 2015-11-25

ace-isearch doesn't work. Although the mode says it's active, C-s performs vanilla search. Reloading my identically configured emacs 24.5, ace-isearch works properly. 

There are no errors to see, so any debugging advice is welcome. Note that ace-jump (to line), and ace-zap still work as expected.

**Comment by tam17aki** [comment] 2015-11-27 02:07
Thank you very much for using ace-isearch and reporting the problem in Emacs 25.

I guess the source code of the isearch package in Emacs 25 has changed from Emacs 24.
Unfortunately, my emacs version is 24.4 and I don't use any dev. version.
Therefore I can't reproduce the problem and give you any useful advice for now.

Best regards,
Akira

**Comment by WorldsEndless** [comment] 2015-12-05 17:31
I noticed that in my Emacs 25, both Avy and the ace-find-word functions worked fine, so I guess it's just a problem in the search hook that connects it with C-s.

**Comment by tam17aki** [comment] 2015-12-05 23:10
Thank you very much for giving me useful information.
I will keep it in mind.

Best regards,
Akira

**Comment by tam17aki** [comment] 2016-08-04 04:53
Hi,

I found the following patch, workaround for Emacs 25.1-rc1:
https://github.com/niku/ace-isearch/commit/ba0b3cac35f2032ee0b5933c98644d4804638e46

Please try it.

Best regards,
Akira

**Comment by cslux** [comment] 2016-08-04 17:18
> Hi,
> 
> I found the following patch, workaround for Emacs 25.1-rc1:
> niku@ba0b3ca
> 
> Please try it.
> 
> Best regards,
> Akira

Works for me in Emacs 25.1.50.1. `isearch-word` is an obsolete variable (as of 25.1), you should now use `isearch-regexp-function` instead.

regards,
Christian

**Comment by tam17aki** [comment] 2016-11-11 11:29
I have tried to fix this problem.
Please try the latest version on melpa.

Best regards,
Akira

**Comment by tam17aki** [comment] 2016-11-18 07:40
I will close this issue temporary.
If you find any problem, please open it.

**Closed by tam17aki** 2016-11-18 07:40 UTC
